### ISSUE TITLE
a go: left after using go: to another page by automatch

### ISSUE THREAD

**Issue by zhangshea** [inns/mak#2] opened 2017-09-13 12:52 UTC
like I have three pages named 

1. `week1network`
2. `week1advdb`
3. `classes`

and when I am in `classes` page now, and I type `go:week1`, mak will gave the automatch list for me and the first of list is the target page `week1advdb` , then I type enter, mak will take me to the page named `week1advdb` and I continue my writing there.

But, there will be a `go:week1` left in page `classes`. I think this is not a feature.

Here is a photograph about the issue:
<img width="388" alt="issue" src="https://user-images.githubusercontent.com/3183515/30378348-7ab893ce-98c5-11e7-9d3a-e6ca61bb3886.png">

**Comment by quietshu** [comment] 2017-09-13 20:21
I think that's an issue caused by the matching RegEx which stopped at the `1`.

**Comment by quietshu** [comment] 2017-09-19 06:18
Fixed in http://mak-beta.shud.in. Will deploy with next version.

**Closed by quietshu** 2017-09-19 06:18 UTC
